name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: dev-duckorm
          POSTGRES_PASSWORD: postgres123
          POSTGRES_DB: dev-duckorm
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Wait for services to start
        run: docker-compose exec -T app sh -c 'until nc -z db 5432; do sleep 1; done'

      - name: Run tests
        run: make local/test

      - name: Stop services
        run: docker-compose down