name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Run tests
        env:
            DATABASE_TEST_URL: ${{ secrets.DATABASE_TEST_URL }}
        run: make local/test

      - name: Stop services
        run: docker-compose down