name: Publish Package

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Authenticate with PyPI
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

      - name: Publish Package
        run: poetry publish --build -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}